# Generated by Django 5.1.5 on 2025-01-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirts',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shirts',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
