# Generated by Django 5.1.5 on 2025-02-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rogue', '0002_alter_shirts_price_alter_shirts_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='shirts.jpg', upload_to='Shirts/')),
                ('brandname', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Formals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='shirts.jpg', upload_to='Shirts/')),
                ('brandname', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hoodies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='shirts.jpg', upload_to='Shirts/')),
                ('brandname', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jackets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='shirts.jpg', upload_to='Shirts/')),
                ('brandname', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='Jeans.jpg', upload_to='Jeans/')),
                ('brandname', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trousers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='shirts.jpg', upload_to='Shirts/')),
                ('brandname', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TShirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='shirts.jpg', upload_to='all_tshirts/')),
                ('brandname', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='shirts',
            name='image',
            field=models.ImageField(default='shirts.jpg', upload_to='Shirts/'),
        ),
    ]
