# Generated by Django 5.1.5 on 2025-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rogue', '0003_cargos_formals_hoodies_jackets_jeans_trousers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='all_watches')),
                ('brandname', models.CharField(max_length=150)),
                ('size', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='all_glasses')),
                ('brandname', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Watches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='all_watches/')),
                ('brandname', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cargos',
            name='image',
            field=models.ImageField(upload_to='all_cargos/'),
        ),
        migrations.AlterField(
            model_name='formals',
            name='image',
            field=models.ImageField(upload_to='all_formals/'),
        ),
        migrations.AlterField(
            model_name='hoodies',
            name='image',
            field=models.ImageField(upload_to='all_hoodies/'),
        ),
        migrations.AlterField(
            model_name='jackets',
            name='image',
            field=models.ImageField(upload_to='all_jackets/'),
        ),
        migrations.AlterField(
            model_name='jeans',
            name='image',
            field=models.ImageField(upload_to='all_jeans/'),
        ),
        migrations.AlterField(
            model_name='shirts',
            name='image',
            field=models.ImageField(upload_to='all_shirts/'),
        ),
        migrations.AlterField(
            model_name='trousers',
            name='image',
            field=models.ImageField(upload_to='all_trousers/'),
        ),
        migrations.AlterField(
            model_name='tshirts',
            name='image',
            field=models.ImageField(upload_to='all_tshirts/'),
        ),
    ]
