# Generated by Django 5.1.5 on 2025-02-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rogue', '0005_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
