# Generated by Django 5.1.5 on 2025-02-04 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rogue', '0006_delete_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='footwear',
            name='color',
            field=models.CharField(default='Black', max_length=60),
        ),
        migrations.AlterField(
            model_name='cargos',
            name='image',
            field=models.ImageField(upload_to='all_cargos'),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='image',
            field=models.ImageField(upload_to='all_footwear'),
        ),
        migrations.AlterField(
            model_name='formals',
            name='image',
            field=models.ImageField(upload_to='all_formals'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='image',
            field=models.ImageField(upload_to='all_glasses/'),
        ),
        migrations.AlterField(
            model_name='hoodies',
            name='image',
            field=models.ImageField(upload_to='all_hoodies'),
        ),
        migrations.AlterField(
            model_name='jackets',
            name='image',
            field=models.ImageField(upload_to='all_jackets'),
        ),
        migrations.AlterField(
            model_name='jeans',
            name='image',
            field=models.ImageField(upload_to='all_jeans'),
        ),
        migrations.AlterField(
            model_name='shirts',
            name='image',
            field=models.ImageField(upload_to='all_shirts'),
        ),
        migrations.AlterField(
            model_name='trousers',
            name='image',
            field=models.ImageField(upload_to='all_trousers'),
        ),
        migrations.AlterField(
            model_name='tshirts',
            name='image',
            field=models.ImageField(upload_to='all_tshirts'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
