# Generated by Django 5.1.5 on 2025-02-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rogue', '0009_alter_cart_product_id_alter_cart_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargos',
            name='size',
        ),
        migrations.RemoveField(
            model_name='footwear',
            name='size',
        ),
        migrations.RemoveField(
            model_name='formals',
            name='size',
        ),
        migrations.RemoveField(
            model_name='hoodies',
            name='size',
        ),
        migrations.RemoveField(
            model_name='jackets',
            name='size',
        ),
        migrations.RemoveField(
            model_name='jeans',
            name='size',
        ),
        migrations.RemoveField(
            model_name='shirts',
            name='size',
        ),
        migrations.RemoveField(
            model_name='trousers',
            name='size',
        ),
        migrations.RemoveField(
            model_name='tshirts',
            name='size',
        ),
    ]
