# Generated by Django 5.1.5 on 2025-02-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rogue', '0010_remove_cargos_size_remove_footwear_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footwear',
            name='color',
            field=models.CharField(max_length=60),
        ),
    ]
